/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9d186315-628c-49de-aa2b-33d5f79f67ab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qxvDf7FlH",
    "aws_user_pools_web_client_id": "7h7elkhsk5qfm59iu06tapo4n7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tbd7dwk4y5fczofwfgyoc42fti.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ouhsq7l2lba2fnczfnwgrhzray"
};


export default awsmobile;
